Merge branch 'main' of https://github.com/dirtybug/radioAmadorCat2exame
RadioEscola-pt/radioescola-v1 pull request #37
Opened 2023-09-11 17:38 UTC by jcalado

2023-09-11 19:00 UTC, alex9099 commented
No geral está top! 
Obrigado pela contribuição

Um bug critico que tem de ser retificado antes de dar merge é ao ver todas as perguntas, só aparece o seletor até às 200
![image](https://github.com/dirtybug/radioAmadorCat2exame/assets/7517045/7534823c-2ab2-4bdf-a0b7-5c9396b21840)

Fora isso, outras coisas que podem ser retificadas mais tarde (ou por nós ou por ti):
- Timer não está centrado verticalmente
- Relativo à paginação de todas as perguntas, talvez usar numero de pagina em vez do numero da primeira pergunta (que nem é a zero)
- A fonte está porreira, mas, na minha opinião (tem de se ver com os restantes membros) preferiria não depender do CDN da google (ou similares), o mesmo se aplica às imagens no rodapé

Diz me o que achas para saber o que pode logo ser retificado e o que passa a issue

2023-09-12 18:41 UTC, jcalado commented
O selector de páginas atualmente parece-me não ser a melhor opção para o problema da paginação, mas acho que será preciso reescrever uma parte da navegação.
O ideal tb seria ter esse código reutilizado, porque só alterei na parte de simular o quiz, e não alterei nessa parte de mostrar as perguntas todas.

Talvez um paginador "clássico" que mostre "1 | 2 | ... | 200 | 201" ou seja omitindo as páginas do meio.
Isso e um botão no fim de cada página para avançar para a página seguinte em vez de ir ao topo da página/barra.

2023-09-12 20:09 UTC, jcalado commented
Penso que com estas alterações fica corrigido o problema da página cortada (para já), e o timer passa a ficar alinhado.

2023-09-12 20:23 UTC, alex9099 requested changes

2023-09-12 20:23 UTC, alex9099 commented on style.css
> +  overflow: hidden;
```
overflow-x: scroll;
overflow-y: hidden;
```
Julgo que seja melhor, de outra forma não há forma de mover os botões das paginas

2023-09-12 20:24 UTC, alex9099 commented
Penso que seja só isso e está pronto a dar merge!
Novamente obrigado pela contribuição :)

2023-09-12 21:02 UTC, merged